server:
  port: 8080
# datasource
spring:
  datasource:
    #数据库名称：mp
    url: jdbc:mysql://192.168.2.118:3306/hongfeiBest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.2.118
    port: 6379
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 8
logging:
  config: classpath:log4j.properties